version: "3.7"

services:
  hq-app:
    container_name: hq-app
    image: ginomassei/hq-front:latest
    ports:
      - "80:80"
    networks:
      - network_hq
networks:
  network_hq:
    name: network_hq
